apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab3_frontend
  template:
    metadata:
      labels:
        app: lab3_frontend
    spec:
      containers:
      - name: frontend-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: lab3-config
              key: REACT_APP_USERNAME
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: lab3-config
              key: REACT_APP_COMPANY_NAME
        ports:
        - containerPort: 3000
